### ISSUE TITLE
Too lazy

### ISSUE THREAD

**Issue by TominoCZ** [LapisSea/lighting-launcher#1]
Yeah.

**Comment by LapisSea** [comment]
Thank you, your report was taking in to consideration.
Consider this problem fixed in 48 hours.

**Comment by TominoCZ** [comment]
Ok <4

**Comment by LapisSea** [comment]
number 15

**Comment by TominoCZ** [comment]
burger king

**Comment by LapisSea** [comment]
foot lettuce

**Comment by TominoCZ** [comment]
the last thing

**Comment by LapisSea** [comment]
https://twitter.com/TheLapisSea/status/975388130097467398
